"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"

# Choose file structure in Crowdin
# e.g. true or false
"preserve_hierarchy": true

# Files configuration
files: [
  {
    # Source files filter
    # e.g. "/resources/en/*.json"
    "source": "src/vindex/**/messages.pot",

    # Where translations will be placed
    # e.g. "/resources/%two_letters_code%/%original_file_name%"
    "translation": "/%original_path%/%two_letters_code%.po",
  }
]
