name: Download from Crowdin

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    environment: Crowdin
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version: 3.12

      - name: Setup project
        run: |
          poetry install --with dev
          poetry run prisma generate

      - name: Generate messages.pot
        run: poetry run poe translate

      - name: Download from Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false

          download_translations: true
          download_sources: false

          pull_request_assignees: ${{ github.actor }}
          pull_request_title: 'chore(i18n): Update translations files'
          pull_request_body: 'This PR was automatically generated by the [crowdin/github-action]. Ensure there is no errors. Project is available at https://crowdin.com/project/vindex'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_KEY }}
