name: Download from Crowdin

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    environment: Crowdin
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          cache-dependency-path: |
            pdm.lock
            pyproject.toml
          python-version: 3.12

      - name: Setup project
        run: |
          pdm install --dev
          pdm run prisma generate

      - name: Generate messages.pot
        run: pdm run translate

      - name: Download from Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false

          download_translations: true
          download_sources: false

          pull_request_assignees: ${{ github.actor }}
          pull_request_title: 'chore(i18n): Update translations files'
          pull_request_body: 'This PR was automatically generated by the [crowdin/github-action]. Ensure there is no errors. Project is available at https://crowdin.com/project/vindex'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_VINDEX_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_VINDEX_API_TOKEN: ${{ secrets.CROWDIN_API_KEY }}
