name: Upload to Crowdin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: Crowdin
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          cache-dependency-path: |
            pdm.lock
            pyproject.toml
          python-version: 3.12

      - name: Setup project
        run: |
          pdm install --dev
          pdm run prisma generate

      - name: Generate messages.pot
        run: pdm run translate

      - name: Upload to Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false

          download_sources: false
          download_translations: false

        env:
          CROWDIN_VINDEX_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_VINDEX_API_TOKEN: ${{ secrets.CROWDIN_API_KEY }}
